//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Проект.DATABASE_CONNECTION
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Invoice = new HashSet<Invoice>();
            this.OrderUser = new HashSet<OrderUser>();
        }
    
        public int idUser { get; set; }
        public string NameUser { get; set; }
        public string SerNameUser { get; set; }
        public string PatronymUser { get; set; }
        public string PhoneNumberUser { get; set; }
        public string Email { get; set; }
        public int Sex { get; set; }
        public System.DateTime DataOfBirth { get; set; }
        public string Adress { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderUser> OrderUser { get; set; }
        public virtual Sex Sex1 { get; set; }
    }
}
