//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Проект.DATABASE_CONNECTION
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public int idDelivery { get; set; }
        public int idTovar { get; set; }
        public int idSuppler { get; set; }
        public int CountTovar { get; set; }
        public Nullable<System.DateTime> DateDelivery { get; set; }
    
        public virtual Tovar Tovar { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
