//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Проект.DATABASE_CONNECTION
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.OrderUser = new HashSet<OrderUser>();
        }
    
        public int idInvoce { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<int> idSuppler { get; set; }
        public Nullable<decimal> FinalCost { get; set; }
        public Nullable<System.DateTime> DataComplite { get; set; }
        public Nullable<int> StatusInvoce { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual StatusInvoce StatusInvoce1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderUser> OrderUser { get; set; }
    }
}
