//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Проект.DATABASE_CONNECTION
{
    using System;
    using System.Collections.Generic;
    
    public partial class listdelivery_tovar
    {
        public int idDelivery { get; set; }
        public int CountTovar { get; set; }
        public Nullable<System.DateTime> DateDelivery { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public string NameTovar { get; set; }
        public string NameTypeTovar { get; set; }
        public string NameSuppler { get; set; }
    }
}
