//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Проект.DATABASE_CONNECTION
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderUser
    {
        public int idOrder { get; set; }
        public int idUser { get; set; }
        public int idTovar { get; set; }
        public int CountTovar { get; set; }
        public Nullable<int> idStatus { get; set; }
        public Nullable<int> idStuff { get; set; }
        public Nullable<System.DateTime> DataComplite { get; set; }
        public Nullable<int> Invoce { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual Stuff Stuff { get; set; }
        public virtual Tovar Tovar { get; set; }
    }
}
