//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Проект.DATABASE_CONNECTION
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHOW_Users_by
    {
        public int idUser { get; set; }
        public string NameUser { get; set; }
        public string PatronymUser { get; set; }
        public string SerNameUser { get; set; }
        public string Adress { get; set; }
        public System.DateTime DataOfBirth { get; set; }
        public int Sex { get; set; }
        public string Email { get; set; }
        public string PhoneNumberUser { get; set; }
    }
}
