//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Проект.DATABASE_CONNECTION
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stuff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stuff()
        {
            this.OrderUser = new HashSet<OrderUser>();
        }
    
        public int idStuff { get; set; }
        public string Name { get; set; }
        public string SerName { get; set; }
        public string Patronym { get; set; }
        public System.DateTime DateofBirthday { get; set; } = DateTime.Now;
        public string PhoneNumber { get; set; }
        public string Adress { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int Role { get; set; }
        public int Sex { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderUser> OrderUser { get; set; }
        public virtual RoleUser RoleUser { get; set; }
        public virtual Sex Sex1 { get; set; }
    }
}
