//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Проект.DATABASE_CONNECTION
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar_Sold
    {
        public string NameTovar { get; set; }
        public Nullable<int> SumTovar { get; set; }
    }
}
