//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Проект.DATABASE_CONNECTION
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_Tovar_status_2
    {
        public int idUser { get; set; }
        public string NameTovar { get; set; }
        public int CountTovar { get; set; }
        public decimal CostTovar { get; set; }
        public Nullable<decimal> Sum { get; set; }
        public Nullable<int> idStatus { get; set; }
    }
}
